version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      js-deps:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns:
          - "*"
