version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
