[package]
name = "painting-droid-core"
version = "0.1.0"
authors = ["Mateusz Migas"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
