name: Validate

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install packages
        run: pnpm install --prefer-offline

      - name: Validate
        run: pnpm run -r validate
