name: Validate

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  validate:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install packages
        run: pnpm install --prefer-offline

      - name: Install browsers
        run: pnpm --filter @painting-droid/web test:e2e:install-browsers

      - name: Run unit tests, typeScript checks and linting
        run: pnpm validate

      - name: Run e2e tests
        run: pnpm --filter @painting-droid/web test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
