name: Validate

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install packages
        run: pnpm install --prefer-offline

      - name: Validate
        run: pnpm run validate
